// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybsrjbbxpwtgcfttrfzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlic3JqYmJ4cHd0Z2NmdHRyZnpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NTM2NTksImV4cCI6MjA2NTEyOTY1OX0.TJrXCFgF7Ctp9qJXgXArBUc-_M7UwtmmOfgbIpmbWVk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);